### ISSUE TITLE
플레이어-장애물 오브젝트 겹침 문제

### ISSUE THREAD

**Issue by jiyeonUning** [karrk/NetworkTeamproject#26]
## 어떤 버그인가요?

> 장애물 오브젝트의 속도가 빠를수록 플레이어의 모델과 서로 겹치는 문제가 발생함.

## 어떤 상황에서 발생한 버그인가요?

```
public class OBJ_Hurdle_Roller : MonoBehaviour
{
   // Given
    [SerializeField] private Vector3 rotate;

    private void FixedUpdate()
    {
       // When
        transform.Rotate(rotate);
    }

    // Then
    private void OnCollisionEnter(Collision collision)
    {
        if (collision.gameObject.CompareTag("Player"))
        {
            Debug.Log("회전 장애물 피격당함!");
        }
    }
}

```

## 예상 결과

> 플레이어 모델 ~ 장애물 모델 사이의 겹침이 최소화 하여, 게임 실제 플레이 시 겹침 문제에 대한 문제 사항을 플레이어가 느끼지 못할 정도를 문제 완료 수준으로 설정함.

**Comment by karrk** [comment]
Transform을 활용한 위치변경은 물리충돌에 적합하지 않습니다.
현재 rigidbody의 angularVelocity, torque 값을 활용해 캐릭터과 캐릭터가 겹치는 현상이 많이 사라졌습니다.
